blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/kasiapps/framework/pulls
    about: 'For ideas or feature requests, send in a pull request'
  - name: Support Questions & Other
    url: https://docs.kasiapp.com/contributions#support-questions
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: Documentation issue
    url: https://github.com/kasiapps/docs
    about: For documentation issues, open a pull request at the kasiapps/docs repository
