name: Release

on:
  workflow_call:

jobs:
  release:
    name: Run Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.semantic.outputs.version }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Run semantic-release and capture outputs
          bunx semantic-release

          # Check if a release was created by looking for new tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LATEST_TAG" ]; then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
            echo "Released version: $LATEST_TAG"
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "version=" >> $GITHUB_OUTPUT
            echo "No release created"
          fi
