name: 'Framework Subsplit'

on:
  workflow_call:
    inputs:
      released:
        description: 'Whether a release was created'
        required: false
        type: string
        default: 'false'
      version:
        description: 'Version tag that was released'
        required: false
        type: string
        default: ''

jobs:
  split:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Compile splitsh-lite
        run: |
          # Install required packages for libgit2 (use Ubuntu 22.04 compatible version)
          sudo apt-get update
          sudo apt-get install -y libgit2-1.1-dev pkg-config build-essential

          # Clone and compile splitsh-lite
          git clone https://github.com/splitsh/lite.git splitsh-lite-source
          cd splitsh-lite-source
          go build -o ../bin/splitsh-lite github.com/splitsh/lite
          cd ..
          rm -rf splitsh-lite-source

          # Make executable and verify
          chmod +x bin/splitsh-lite
          ./bin/splitsh-lite --version

      - name: Run split script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e  # Exit on any error

          # Verify GITHUB_TOKEN is available
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Error: GITHUB_TOKEN is not set"
            exit 1
          fi

          # Make scripts executable
          chmod +x ./bin/split.sh ./bin/release.sh ./bin/splitsh-lite

          # Check if this was called from main workflow with release info
          if [[ "${{ inputs.released }}" == "true" && -n "${{ inputs.version }}" ]]; then
            echo "Release detected from main workflow: ${{ inputs.version }}"
            echo "Running release script for tag splitting and tagging"
            bash ./bin/release.sh "${{ inputs.version }}"
          # Check if this is a direct tag push
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "Tag push detected: $TAG_NAME"
            echo "Running release script for tag splitting and tagging"
            bash ./bin/release.sh $TAG_NAME
          # Otherwise it's a branch push
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "Branch push detected: $BRANCH_NAME"
            echo "Running split script for branch splitting"
            bash ./bin/split.sh
          fi
