name: Testing

on:
  workflow_call:
    inputs:
      ref:
        description: 'The ref to test'
        required: false
        type: string
        default: ''

jobs:
  tests:
    runs-on: ubuntu-24.04
    name: Tests (PHP ${{ matrix.php }})

    strategy:
      matrix:
        php: [8.3, 8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run static analysis
        run: composer analyse

      - name: Execute tests
        run: vendor/bin/pest
